language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures: [hhvm]

before_script:
  - composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpspec run --format=pretty -vvv
  - vendor/bin/php-cs-fixer fix src --dry-run --diff
